### ISSUE TITLE
afterChange not firing when number of slides is less than slidesToShow

### ISSUE THREAD

**Issue by henryw14** [kenwheeler/slick#1245]
Look at this <a href="http://jsfiddle.net/o33x6fux/">jsfiddle</a>. I would think that even if the number of slides is less than slides to show, with centermode enabled, clicking on one of the slides would activate it, cause the afterChange event to occur if it was a change, and center the slide. With this sort of initialization:
```
 $('.single-carousel').on('afterChange', function(slick, slide){
            console.log("changing index");
            // left
        });
        $('.single-carousel').slick({
            centerMode: true,
           centerPadding: '60px',
            slidesToShow: 3,
            dots: true,
            focusOnSelect: true,
            infinite: false,
            responsive: [
                {
                    breakpoint: 2140,
                    settings: {
                        arrows: true,
                        centerMode: true,
                        centerPadding: '40px',
                        slidesToShow: 3
                    }
                },
                {
                    breakpoint: 768,
                    settings: {
                        arrows: true,
                        centerMode: true,
                        centerPadding: '40px',
                        slidesToShow: 3
                    }
                },
                {
                    breakpoint: 480,
                    settings: {
                        arrows: false,
                        centerMode: true,
                        centerPadding: '40px',
                        slidesToShow: 1
                    }
                }
            ]
        });
```
I do not see the desired behavior. Am I doing something incorrectly or is this a bug? When I inspect which slide is active, either via the classes on the slide itself or by observing the `currentSlide` property, the active index is changing. Why isn't the afterChange event firing in the second case?

**Comment by henryw14** [comment]
Any update on this? It's breaking something I am trying to get into production

**Comment by slavicd** [comment]
Same problem, without the center mode. None of the change events seem to fire when doing .slick("slickNext") or slick("slickGoTo", nr) .

**Comment by slavicd** [comment]
I have fixed the 1.5.9 version to correctly account for this situation. Since I'm not sure about whether it broke other configurations of the slider here's a gist that you can a) see where the problem is with; a) use as a temporary fix.

https://gist.github.com/slavicd/4a5aee536060a9bc9344c792154ad899

**Comment by rvanlaarhoven** [comment]
@slavicd The fix in your gist does trigger the goTo events, but ignores the centerMode.

**Comment by robsilva** [comment]
I am running version 1.6.0 but it still not working correctly for me.

I am not using centerMode but I am calling 'slickNext()' in a different method after the initialization.

`	$('#questions').slick({
	  infinite: false,
	  slidesToShow: 1,
	  slidesToScroll: 1,
	  dots: false,
	  arrows: false,
	  swipe: false,
	 	onAfterChange: function(e) {
	 		console.log("This never fires");
    }
});

$('.btn-next').click(function(){
    	$("#questions").slick('slickNext');
});

`

Any idea why? Thanks in advance!

**Comment by leggomuhgreggo** [comment]
@henryw14 I think this is resolved now, but definitely holler back if I'm missing something.

@robsilva no longer use that method for events. It'd be:
`$('#questions').on('afterChange', function(){  ...code... })`

**Comment by MagieUltime** [comment]
I seem to be running into a problem very similar to this one!
In my case, the afterChange is not firing if the number of slides is lower than the slidesToShow number. I'm using version 1.6.0 and I'm not using center mode.

In my example, I'm using 2 slick instances synced together for a little video gallery. I use the first slick instance to display the video, and the second instance serves as a thumbnail navigation. The problem is that it's user generated content and there may be between 1 and an infinite number of videos. Right now, I only have 2 slides available and the slidesToShow number is set to 4 for my thumbnail navigation slick. I'm trying to trigger an alert when the slides change, but the function is not firing. I tested and the function DO trigger when I have a bigger number of slides than the slidesToShow number!

Am I missing something or is there something wrong with my code that I do not see?

JS:
`$('.slick-main .slick').slick({
	slidesToShow: 1,
	slidesToScroll: 1,
	asNavFor: '.slick-thumbs .slick',
	arrows: false,
	fade: true,
	draggable: false
});
$('.slick-thumbs .slick').slick({
	slidesToShow: 4,
	slidesToScroll: 1,
	asNavFor: '.slick-main .slick',
	arrows: true,
	prevArrow: '.slick-thumbs .slick-nav-prev',
	nextArrow: '.slick-thumbs .slick-nav-next',
	centerMode: false,
	focusOnSelect: true,
	draggable: false
});

$('.slick-thumbs .slick').on('afterChange', function(){
	alert('Slide changed!');
});`

HTML:
`<div class="slick-hold slick-main">
	<div class="slick">
		<div class="slick-slide"><iframe id="video1" class="video" width="1920" height="1080" src="https://www.youtube.com/embed/wN8_eb3l0mw?enablejsapi=1;rel=0&amp;controls=1&amp;showinfo=0" frameborder="0" allowfullscreen></iframe></div>
		<div class="slick-slide"><iframe id="video1" class="video" width="1920" height="1080" src="https://www.youtube.com/embed/wN8_eb3l0mw?enablejsapi=1;rel=0&amp;controls=1&amp;showinfo=0" frameborder="0" allowfullscreen></iframe></div>
	</div>
</div>
<div class="slick-hold slick-thumbs">
	<div class="slick-nav slick-nav-prev">Prev</div>
	<div class="slick-nav slick-nav-next">Next</div>
	<div class="slick">
		<div class="slick-thumb">Title 1</div>
		<div class="slick-thumb">Title 2</div>
	</div>
</div>`

**Comment by ahallock** [comment]
Running into the same issue with `afterChange` when all slides are visible and using `focusOnSelect: true`. Selecting a slide doesn't fire the `afterChange` event.

**Comment by masteratt** [comment]
I'm having the exact same issue as the two posts above....Any help would be appreciated.

**Comment by cameroncowden** [comment]
+ 1 for this issue. Found a workaround. 

My setup was slightly different, essentially needed to have 1 slider (in a modal) that would show different information depending on which product was being "quick viewed". 
The slider could contain between 4-20 slides. We want to show 4 at a time (always).

If there were 4 slides exactly, and slidesToShow = 4, then neither beforeChange or afterChange events are fired. Class .slick-current moves around appropriately, though. Worth noting that in this setup, there is no desired movement in the slider (for this edge case only).

Workaround was to bind event listeners on the inner items themselves from within an init listener.
The init Listener fires every time the modal is opened (slick unslicked, slides wiped, slides added, reslicked), and then spins out listeners for those particular slides (which are purged when modal is closed).
```
$('#qv-swatches').on('init', function(event,slick){
        	console.log(slick);
        	$('#qv-swatches').resize(); //to correct display issue
        
        	var rad = document.qvswatches.selectprint;
            var prev = null;
            for(var i = 0; i < rad.length; i++) {
                rad[i].onclick = function(event) {
                  	event.stopPropagation();
                    (prev)? console.log("no longer showing " + prev.value):null;
                    if(this !== prev) {
                        prev = this;
                    }
                    console.log("now showing " + this.value)
                    current_print = this.value;
                  	getPrint(current_print);
                };
            }
        });
```
