### ISSUE TITLE
Animation issues when going from last to first item.

### ISSUE THREAD

**Issue by raphaelparent** [kenwheeler/slick#3560]
When I try to animate the slide transition with some opacity, everything works fine except when I go forward from last to first element. Even when I go backward from first to last it works fine.

[.gif of the issue](https://imgur.com/a/SPuzZsx)

The gif is a bit more glitchy than the actual result but we can clearly see that when going from slide "4" to "1" the animation skips. But not when going from slide "1" to "4".

###### `[  https://jsfiddle.net/b5bqk68j/6741/  ]`  

====================================================================

#### Steps to reproduce the problem

1. Initialize a slick slider with the following config
    ```
    let sliderConfig = {
        centerMode: true,
        centerPadding: '400px',
        infinite: true,
        slidesToShow: 1,
        prevArrow: $prevArrow,
        nextArrow: $nextArrow
    };
    ```
2. Add transition to slide or element in the slide.
    in my case:
    ```
    .slick-animate {
        opacity: 0.5;
        transition: opacity 0.48s ease-in-out;
    }
    .slick-center {
        .slick-animate {
           opacity: 1;
       }
    }
    ```

3. Use any means of going forward through the slides and see the effect.

====================================================================

#### What is the expected behaviour?

Every slides animates properly (like when going backwards).

====================================================================

#### What is observed behaviour?

When going from last to first the animation is glitching. (probably because of the slide cloning/switching)

====================================================================

**Comment by explorador** [comment]
I had this same issue. I ended up replacing line 2356 https://github.com/kenwheeler/slick/blob/master/slick/slick.js Line 2356 
`allSlides
	.eq(_.slideCount - 1 - _.options.slidesToShow)
	.addClass('slick-center');
`
with
`
allSlides
	.eq( indexOffset + _.slideCount + 1 )
	.addClass('slick-center');
`

**Comment by raphaelparent** [comment]
Thanks for answering.  😄 

Unfortunately I just tried switching out that line but it doesn't seem to change the end results.

I made sure the proper version of the file was loaded and not a cached version but nothing.

**Comment by explorador** [comment]
I updated the code, maybe you used my previous one. Let me know if it works

**Comment by raphaelparent** [comment]
Oh nice that did fix it! Thank you 👍

**Comment by pjfsilva** [comment]
This should be reopened so it's fixed in the library itself. maybe @explorador can send a PR for this?

**Comment by alex88** [comment]
I see the same behavior again, does anyone have the same issue?

I've applied:
```
    .slick-slide
      img
        transition: all 0.5s
    .slick-center
      img
        transform: scale(1.8)
```
and I see the transition ok in all slides except when it restarts from the beginning, the whole sliding animation works fine but the scale is applied only on animation end

**Comment by eleven59** [comment]
Don't know why this is closed since the issue is still here in the latest version. I fixed it in my project by applying a custom class ".slick-target" to the slide that slick is transitioning to (so next or prev slide depending on direction) and then applying CSS to both ".slick-target" and ".slick-current" simultaneously. No delay, just smooth transitions all around.

So JS:
```javascript
let slick = $('.container').slick({'infinite': true});
slick.on('beforeChange', (event, slick, currentSlide, nextSlide) => {
    let nextIndex = currentSlide + 1; // assume moving right
    if(currentSlide-1 == nextSlide || (nextSlide+1 == slick.slideCount && currentSlide < nextSlide)) {
        change = nextIndex = currentSlide - 1; // nope, moving left
    }
    $(`[data-slick-index="${currentSlide+change}"]`).addClass('slick-target');
});
```

And CSS:
```css
/* Not current slide */
.container {
    transform: scale(.8);
    transition: .5s all;
}

/* Current slide */
.slick-current .container,
.slick-target .container {
    transform: scale(1);
}
```

The detection in my JS code of whether we're moving left or right only works for 3+ slides I think, because that was all I needed, but you could change that line to be much much longer if you need to detect this. See [#1679](https://github.com/kenwheeler/slick/issues/1679#issuecomment-140493213).

**Comment by Thom711** [comment]
This saved my ass, thanks eleven59!

**Comment by duongan** [comment]
You just saved my day @eleven59. Thanks a lot!
