### ISSUE TITLE
Can't destroy slick - unslick function returns error

### ISSUE THREAD

**Issue by simonkitson** [kenwheeler/slick#369]
I'm unable to destroy a slick instance. Calling `$('.your-slider').unslick();` returns `Uncaught TypeError: Cannot read property 'parent' of null` on line 575 of slick.js. It would appear `$slides` is undefined. Is anyone else seeing this issue?

**Comment by richlewis14** [comment]
HI All, I too am having an issue when calling unslick, i get this error 

`TypeError: _.$slides is null if (_.$slides.parent().hasClass('slick-track'))`

I have created a StackOverflow with a detailed account of the scenario <a href="http://stackoverflow.com/questions/27798824/unslick-method-not-working" target="_blank">here</a>

Any assistance would be greatly appreciated

**Comment by kenwheeler** [comment]
@richlewis14 why do you have 3 slick clones in a row? Can I see a jsfiddle?

**Comment by dan-diaz** [comment]
@richlewis14 
Check out my thoughts on this.
http://stackoverflow.com/questions/27798824/unslick-method-not-working/27928917#27928917

**Comment by dan-diaz** [comment]
@richlewis14 
check out my comments on this.
http://stackoverflow.com/questions/27798824/unslick-method-not-working/27928917#27928917

**Comment by Worstkaes** [comment]
Thanks @flesch91! Your answer works fine for me!

**Comment by syren** [comment]
I followed these instructions but it's still not working. I keep getting the same error "Uncaught TypeError: Cannot read property 'parent' of null".

I'm trying to do the opposite and kill the slideshow on mobile. Please help :)

    var carousel = $j('.fundraiser-list');

    function showSliderScreen($screenWidth) {
        if($screenWidth >= "480") {
            if(!carousel.hasClass('slick-initalized')){
                carousel.slick({
                    responsive: [
                        {
                            breakpoint: 2100,
                            settings: {
                                slidesToShow:5
                            }
                        },
                         {
                            breakpoint: 1550,
                            settings: {
                                slidesToShow: 4
                            }
                        },
                        {
                            breakpoint: 1250,
                            settings: {
                                slidesToShow: 3
                            }
                        },
                        {
                            breakpoint: 768,
                            settings: {
                                slidesToShow: 2
                            }
                        },
                        {
                            breakpoint: 480,
                            settings: {
                                slidesToShow: 1
                            }
                        }
                    ]
                });
            }
        } else {
            console.log("smaller than 480");
            if (carousel.hasClass('slick-initialized')) {
                carousel.unslick();
            }
        }
    }

    var screenWidth = $j(window).width();
    $j(window).ready(showSliderScreen(screenWidth)).resize(function(){
        var screenWidth = $j(window).width();
        showSliderScreen(screenWidth);
    });

**Comment by adamhughes86** [comment]
Not sure if anyone is still looking at this but I was stuck on it for an hour. I realised I have either read the way you call methods wrong or it's changed. 

Instead of 
carousel.unslick();

You should use
carousel.slick("unslick");

**Comment by EnigmaSolved** [comment]
Yeah, calling methods was recently changed:
https://github.com/kenwheeler/slick/releases/tag/1.4.0

**Comment by aosmichenko** [comment]
not working for me having this issue:
 Uncaught TypeError: Cannot read property 'removeClass' of nullslick.min.js?ver=20140101:694 Slick.destroyslick.min.js?ver=20140101:2082 
Slick.unslickslick.min.js?ver=20140101:2143 
$.fn.slickcustom.js?ver=20140101:73 
(anonymous function)jquery.js?ver=1.11.1:3 
m.event.dispatchjquery.js?ver=1.11.1:3 
m.event.add.r.handle

<addr>
var aboutLogos = $('#about-logos-box');
	$(window).resize(function(){
		aboutColumns();
		if(window.innerWidth <= 767){
			aboutLogos.slick({
				adaptiveHeight: true,
				autoplay: true,
				arrows: false,
				dots: false,
				autoplaySpeed: 7000
			});
		} else {
			if(aboutLogos.hasClass('slick-initialized')) {
				aboutLogos.slick('unslick');
			}
		}
	});
</addr>

**Comment by rdjoks** [comment]
Has no one been able to solve this issue? Does slick carousel not work properly with dynamically loaded content? Is using it advised? I have included it in my application and am desperately trying to find a solution or an alternative fast.

**Comment by eskater** [comment]
I create function for easy using, set initialSize for every elements
```javascript
slickPush(
[	
	{
		el: '.partner-list',
		settings: { dots: true, arrows: false, infinite: true, speed: 300, slidesToShow: 6, slidesToScroll: 6, responsive: [ { breakpoint: 1024, settings: { slidesToShow: 4, slidesToScroll: 4, infinite: true, dots: true } }, { breakpoint: 768, settings: { slidesToShow: 3, slidesToScroll: 3 } } , { breakpoint: 550, settings: { slidesToShow: 2, slidesToScroll: 2 } } ] },
		initialSize: 0
	},
	
	{
		el: '.review-list',
		settings: { dots: false, arrows: false, infinite: true, centerMode: true, speed: 300, slidesToShow: 6, slidesToScroll: 6, autoplay: true, autoplaySpeed: 3000, responsive: [ { breakpoint: 1024, settings: { slidesToShow: 4, slidesToScroll: 4 } }, { breakpoint: 768, settings: { slidesToShow: 2, slidesToScroll: 2 } } , { breakpoint: 550, settings: { slidesToShow: 1, slidesToScroll: 1 } } ] },
		initialSize: 0,
	},
	
	{
		el: '.we-makeit-items',
		settings: { dots: false, arrows: false, speed: 300, centerMode: true, autoplay: true, autoplaySpeed: 4000, responsive: [ { breakpoint: 1024, settings: { slidesToShow: 3, slidesToScroll: 3 } }, { breakpoint: 768, settings: { slidesToShow: 2, slidesToScroll: 2 } }, { breakpoint: 550, settings: { slidesToShow: 1, slidesToScroll: 1 } } ] },
		initialSize: 768
	},
	
	{
		el: '.our-service-list',
		settings: { dots: false, arrows: false, speed: 300, centerMode: true, responsive: [ { breakpoint: 768, settings: { slidesToShow: 1, slidesToScroll: 1 } } ] },
		initialSize: 768	
	},
	
	{
		el: '.blog-wrap',
		settings: { dots: false, arrows: false, speed: 300 },
		initialSize: 768
	},				
]);
```
function

```javascript
function slickPush(slickEls)
{
	var lastWinSize = 0;
	
	window.onresize = function(e)
	{
		var winSize = $(window).width();
	
		/* resize one time */
		if( lastWinSize == winSize)
		{
			return false;
		}

		/* remember last window size */
		lastWinSize = winSize;
	
		for(var i=0; i<slickEls.length; i++)
		{
			var slickOpts = slickEls[i];

			/* if element not found */
			if( $(slickOpts.el).size() <= 0 )
			{
				continue;
			}
			
			/* get element */
			var el = $(slickOpts.el);
			
			/* for all window size */
			if( slickOpts.initialSize == 0 )
			{
				if( typeof slickOpts.object == 'undefined' )
				{
					slickOpts.object = $(el).slick(slickOpts.settings);
				}
				
				continue;
			}
			
			/* destroy slick for custom win size */
			if( winSize >= slickOpts.initialSize )
			{
				if( typeof slickOpts.object !== 'undefined' )
				{
					$(slickOpts.object).slick('destroy');

					slickOpts.object = undefined;
				}
				
				continue;
			}
			
			/* initial slick for custom win size */
			if( typeof slickOpts.object == 'undefined' )
			{
				slickOpts.object = $(el).slick(slickOpts.settings);
			}
		};
	};
	
	/* run */
	$(window).trigger('resize');	
}	
 
```

**Comment by GenkgoMartijn** [comment]
We had the same problem. It turned out to our own problem: you should avoid to call ```$('element1').slick(options);``` multiple times. If you do, then ```$('element1').slick('unslick')``` causes problems.

**Comment by dmellenthin** [comment]
I resolved "cannot read property 'unslick' of undefined" (on line 2399 of slick.js), by adding the following if before attempting to .apply(...)

if (_[i].slick) ret = _[i].slick[opt].apply(_[i].slick, args);

Not sure if this is advisable, but it seems to be working like a champ for now.

**Comment by simeydotme** [comment]
I'm pretty sure these issues are all fixed now? I can't find one solid example of an issue from the comments and jsfiddles. - unslicking on breakpoints, and the way to call methods was changed (as someone else mentioned) and also recently a bug with `asForNav` trying to reference non-existant, or unslicked-sliders was fixed.

**Comment by deeve007** [comment]
This is still an issue with the latest code. If I unslick at a particular breakpoint, reduce the browser width so it "unslicks", but then expand the browser again wider than that breakpoint, it remains unslicked rather than re-slicking.

**Comment by extractachris** [comment]
+1

**Comment by extractachris** [comment]
@flesch91's solution worked for me!

**Comment by nikitahl** [comment]
@flesch91  you're a lifesaver! Thank you so much for your solution. It work for me.

**Comment by flesch91** [comment]
@nikitahl   May all your dreams come true!  ;)

**Comment by manishagitker** [comment]
@kenwheeler  :  I am getting error in IE 9 console because of unslick .
 **when doing $('.responsive').slick('unslick'); getting error  - **

> _Unable to get value of the property 'unslick': object is null or undefined_

**when doing $('.responsive').unslick(); getting error  - **

> Object doesn't support property or method 'unslick'
 please provide the solution.

**Comment by leggomuhgreggo** [comment]
@manishagitker or anyone else still experiencing this issue, can you recreate in a fiddle?

**Comment by BryanBarrera** [comment]
The issue is still happening.. i am trying to unslick the slider at a certain breakpoint but its giving me this same error.

**Comment by inferusvv** [comment]
Me too. For me works this:

```
var $slider = $('.slider').slick();
$slider.slick('getSlick').reinit();
```

**Comment by ArthurShlain** [comment]
@inferusvv, for me too, but new slick dots added every time when using this code (i need to restore slick width on bootstrap tabs change event).

**Comment by daydarkln** [comment]
My way:
`var isSlicked = false

  if($(window).width() < 768 && !isSlicked) {
    $('.why-chapter__list').slick({
      slidesToShow: 1,
      slidesToScroll: 1,
      prevArrow: gridPrevArrow,
      nextArrow: gridNextArrow,
      // mobileFirst: true,
      // responsive: [{
      //   breakpoint: 1024,
      //   settings: 'unslick',
      // }],
    });
    $('.projects__main .grid-menu__list').slick({
      slidesToShow: 1,
      slidesToScroll: 1,
      prevArrow: gridPrevArrow,
      nextArrow: gridNextArrow,
      centerMode: true,
      centerPadding: '0',
    });
    isSlicked = true;
  }
  //////////////////////////////////////////
  // There's need some way to destroy slick
  // and init it in the future may be.
  // So, we have var isSlicked which control
  // screen size and trigger slider automaticly.
  //////////////////////////////////////////
  $(window).on('resize orientationchange', function() {
    if($(window).width() >= 768 && isSlicked) {
      console.log('destroy');
      $('.why-chapter__list').slick('unslick');
      isSlicked = false;
    } else {
      if($(window).width() < 768 && !isSlicked) {
        $('.why-chapter__list').slick({
          slidesToShow: 1,
          slidesToScroll: 1,
          prevArrow: gridPrevArrow,
          nextArrow: gridNextArrow,
          // mobileFirst: true,
          // responsive: [{
          //   breakpoint: 1024,
          //   settings: 'unslick',
          // }],
        });
        $('.projects__main .grid-menu__list').slick({
          slidesToShow: 1,
          slidesToScroll: 1,
          prevArrow: gridPrevArrow,
          nextArrow: gridNextArrow,
          centerMode: true,
          centerPadding: '0',
        });
        isSlicked = true;
      }
    }
  });`

**Comment by ilkovs** [comment]
Okay, guys.... I've tried all above mentioned ways and I still can't get slick slider to work after the page reloads. The slider works perfect until a button is clicked ( for example to update quantity on item) and the slider is gone.... I tried to slick("unslick") and then reinitialize it, still nothing. Anyone ???

**Comment by BryanBarrera** [comment]
Can you provide a codepen or JS Fiddle? @ilkovs

**Comment by ilkovs** [comment]
@BryanBarrera , my slick logic is the following. In this case, I'm trying to use the Slider for devices under 1024px. But I also tried in general, still brakes on load. I can't provide fiddle, it's an e-commerce theme (handlebars).

$(document).ready(function(){

```
function slickify(){
    event.preventDefault();
    $('.cart-list').not('.slick-initialized').slick({
        infinite: false,
        responsive: [
            {
                breakpoint: 1024,
                autoplay: false,
                dots: true,
                infinite: false,
                settings: {
                    slidesToShow: 3,
                    slidesToScroll: 3,
                    dots: true
                }
            },
            {
                breakpoint: 786,
                autoplay: false,
                dots: true,
                infinite: false,
                settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    dots: true
                }
            },
            {
                breakpoint: 550,
                autoplay: false,
                dots: true,
                infinite: false,
                settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    dots: true
                }
            }
        ]
    });
}

$(window).resize(function(){
    event.preventDefault();
    var $windowWidth = $(window).width();
    if ($windowWidth < 1024) {
        slickify();  
        
        $(window).resize(function() {
            $('.cart-list').slick('resize');
            event.preventDefault();
          });
          
          $(window).on('orientationchange', function() {
            $('.cart-list').slick('resize');
            event.preventDefault();
          });
    }
});
```
});

I tried using any function like 🔽 but nothing seems to fix the issue.

$('body').click(function() {
$('.slider').slick('reInit');
});


As far as destroying and reinitializing I tried the following:

$(document).ready(function() {
   $('.cart-list').slick("unslick");
    $('.cart-list').slick(");
});

**Comment by BryanBarrera** [comment]
When it loads at 1024 does it load? or on resize it breaks?

**Comment by ilkovs** [comment]
@BryanBarrera it loads initially without any issues on any device, but whenever you update something on the page and it reloads with the new values, the slider brakes and I have to manually refresh it again in order to initialize.

**Comment by BryanBarrera** [comment]
Do you get any errors in the console?
What version of slick are you using?
Can you try this in the last function you have above?

`$('.cart-list').slick();` rather than slick('');

**Comment by ilkovs** [comment]
@BryanBarrera the '' is a typo that I did here, but my code is using slick(); sorry about that. I use a CDN instead of uploading the files to the theme. Should be the latest version.

**Comment by BryanBarrera** [comment]
if you add console.log('hey this is a test'); does this load in the console after you update the page and it reloads?

**Comment by ilkovs** [comment]
@BryanBarrera it console loges as it should.

**Comment by BakaySerg** [comment]
**solution for unslick on desktops:**

  var viewportWidth = $(window).width();
  var slickCheck;
  viewportWidth > 576 ? slickCheck = 'unslick': slickCheck = {slidesToShow: 1};

  $('.my__slider').slick({
    slidesToShow: 1,
    slidesToScroll: 1,
    variableWidth: true,
    arrows: false,
    dots: false,
    mobileFirst: true,
    responsive: [
       {
          breakpoint: 550,
          settings: slickCheck
        }
     ]
  });

**Comment by kubik101** [comment]
I'm not a pro but this is what worked for me.
```
function myMobileCarousel() {
	var windowSize = jQuery(window).width();
	if (windowSize <= 991) {
		// slick it
		if (!jQuery('.carousel_mobile').hasClass("slick-initialized")) {
			jQuery('.carousel_mobile').slick({
			  dots: true,
			  infinite: false,
			  slide: 'li',
			  speed: 800, // was 300
			  slidesToShow: 3,
			  slidesToScroll: 3,
			  responsive: [
				{
				  breakpoint: 991,
				  settings: {
					slidesToShow: 2,
					slidesToScroll: 2,
					infinite: false,
					dots: true
				  }
				},
				{
				  breakpoint: 767,
				  settings: {
					slidesToShow: 1,
					slidesToScroll: 1
				  }
				}
			  ]
			});
		}
	} else {
		// unslick
		if (jQuery('.carousel_mobile').hasClass("slick-initialized")) {
			jQuery('.carousel_mobile').slick('unslick');
		}
	}
}

jQuery(document).ready(function(){
	myMobileCarousel();
});

jQuery(window).resize(function(){
	myMobileCarousel();
});

```

**Comment by nini-li** [comment]
thank you @benbowler 👍 🎉 👍 🎉 👍 🎉

but `$carousel.unslick();` not working.

For me works this code:
```
    var $carousel = $('.element_class');
    if ($(window).width() <= 768) {
      if (!$carousel.hasClass('slick-initialized')) {
        $markSlider.slick({
          dots: true,
          arrows: false
        });
      }
    } else {
      if ($carousel.hasClass('slick-initialized')) {
        $carousel.slick('unslick');
      }
    };

  //window resize
  window.onresize = function () {
    markSlick()
  };
```
