### ISSUE TITLE
Sync Slider will not sync when dragging the slides from the main slider

### ISSUE THREAD

**Issue by lukaskoeller** [kenwheeler/slick#903]
I use the sync slider from slick v1.3.15 and have a problem when I use my mouse to drag the slide for navigating through them. the 'nav-slider' contains names, the 'main-slider' the images. When you click through the 'nav-slider' the several names getting highlighted using css and the class ```.slick-active```. But the class ```.slick-active``` didn't change on 'nav-slider' when I navigate 'main-slider' so it's not syncronized anymore.
Up to now I just tested by dragging because I don't use arrows oder pignation for navigation.

**Comment by kenwheeler** [comment]
please provide a jsfiddle.

**Comment by lukaskoeller** [comment]
http://jsfiddle.net/g4o9edne/20/

If you use the navigation (```.name```) everything works fine. If you click on one of them, the ```border-color``` turns red and the image slider slides to the correct image.
If you use the image slider by dragging the slides, the ```.slick-active``` doesn't sync , so the red marked name (from ```.name```) stays where it is. (Sorry for bad english)

**Comment by lukaskoeller** [comment]
And by the way: Why is ```.slick-active``` set on every slide of ```.name``` (everything is red) when reloading the page?
And is there a reason why a sync slider has to own at least one similar element (my jsfiddle wouldn't work if there would be no ```<h3>``` inse ```.image```)?

**Comment by kenwheeler** [comment]
ahh ok. looking into this

**Comment by desandro** [comment]
You might want to try [Flickity](http://flickity.metafizzy.co). It supports [`asNavFor`](http://flickity.metafizzy.co/options.html#asnavfor) like Slick. You can click and swipe on either slider and it'll sync up fine. See demo http://codepen.io/desandro/pen/wByaqj

**Comment by natis** [comment]
Just checking in to see if there is an update to this issue. Having a similar problem where dragging between slides doesn't add the class of slick-active to the companion carousel.

**Comment by ptibbetts** [comment]
Thanks for the code (from your coworker) @natis , it works for me however each of the thumbnails/previews are set to active on page load for some reason and so this doesn't fully work for me.

Getting around it by setting draggable to false for now.

**Comment by jadewelsh** [comment]
I've modified the slick.js code to fix this issue for me.

In the "Slick.prototype.slideHandler" function (around line 2119) remove the if statement:

if (_.slideCount <= _.options.slidesToShow) {
    return;
}

Then farther down (around line 2200), below the "_.updateDots();" and "_.updateArrows();" add in:

if (_.slideCount <= _.options.slidesToShow) {
    _.animating = false;
    return;
}

This worked for me.

**Comment by mvinodpatil** [comment]
Hi,

Can you please look into this?

Thanks.

**Comment by leggomuhgreggo** [comment]
[Updated the fiddle to the master](http://jsfiddle.net/je8jferp/). Looks like this has been fixed. Is there some other issue I'm missing?

**Comment by mphm** [comment]
Updating from 1.5.9 to 1.6.0 fixed it for me.

**Comment by mehne** [comment]
I can say after intensive testing, that this error still exists in Version 1.6 and 1.8.1
