### ISSUE TITLE
infinite scrolling issue

### ISSUE THREAD

**Issue by cottonhen** [kenwheeler/slick#964]
Hi there! Nice work!

I have a problem with infinite scrolling. I'm using Foundation 5 and did a simple slider inside my page:
```
<div class="slick">
<div class="one"><img src="assets/img/oltremedia-orizzontale-white.svg" alt="" width="" height=""></div>
<div class="one"><img src="assets/img/oltremedia-orizzontale-white.svg" alt="" width="" height=""></div>
<div class="one"><img src="assets/img/oltremedia-orizzontale-white.svg" alt="" width="" height=""></div>
<div>
```
and the js:

```
	//slick slider
	$('.slick').slick({
		dots: true,
		infinite:true
	});
```

the slider is working fine but when I'm on the last slide it goes to the right to the first one slide (the cloned one to the right) but immediately after slides left to the very first one... so the "infinite" scrolling effect doesn't work (for me, by the way :-) )

Help would be very apreciated!

bye
Francesco

**Comment by kenwheeler** [comment]
This is fixed on dev

**Comment by cottonhen** [comment]
Did use the dev branch but the problem was still there...
I resolved deleting this line on my scss:
```
* {
	transition: all .5s ease-in-out;
}
```

**Comment by lanthanoider** [comment]
I'm still encountering exactly the same issue with 1.5.8. I'm using Foundation 5 and Laravel. 

When I put the carousel inside a blank HTML file, the infinite looping works well, but it doesn't once I put it into my Laravel blades. Tried basically enabling/disabling all options, still can't get to fix the issue. Any help would be much appreciated!!!

**Comment by lanthanoider** [comment]
I'm still encountering exactly the same issue with 1.5.8. I'm using Foundation 5 and Laravel.

When I put the carousel inside a blank HTML file, the infinite looping works well, but it doesn't once I put it into my Laravel blades. Tried basically enabling/disabling all options, still can't get to fix the issue. Any help would be much appreciated!!!

**Comment by csmith0917** [comment]
I am seeing this issue with a Drupal project. I've stripped out all the regular Drupal junk, still seeing this exact same problem

**Comment by michaelsoriano** [comment]
I'm experiencing the same issue as above - except I'm using Bootstrap. 

When it reaches the last item - it tries to go back to the first slide - but not in the same direction. Instead it goes back opposite. Below is an animated screenshot: 

![Image of InfititeLoop](http://demo.michaelsoriano.com/wp/wp-content/uploads/2015/10/slick-vimi.gif)

Here is the [link to Demo!](http://demo.michaelsoriano.com/wp/) - scroll down to the middle of the page.

Any help is appreciated.

**Comment by tonycoll91** [comment]
I am also having this issue when using Adobe Test and Target. Although i cannot figure out what is happening, I recreated the overall layout in a jsfiddle and it works fine.
