### ISSUE TITLE
Small width screen bug

### ISSUE THREAD

**Issue by badbojo** [kenwheeler/slick#983]
hi
Slick collapsing at a small width of the screen if variableWidth is true.
http://jsfiddle.net/tgyv1g3e/3/
Make screen width <800px to see the bug.

On your site the same effect:
http://gyazo.com/d7069e600c12aa83e738eb239d0f465a

**Comment by jaylinski** [comment]
same here. i could fix it by setting `adaptiveHeight` to `true`.

**Comment by badbojo** [comment]
Do not work for me and jsfiddle also.

**Comment by tomaszpoliszuk** [comment]
ok
http://jsfiddle.net/tgyv1g3e/6/
Bug is probably caused by cloned to long element.
In my opinion it's shouldn't be marked as bug (why you would like create element 1550px width for <800px width viewport?).

tip:
instead
<pre>
.slick-slide:nth-child(1),
.slick-slide:nth-child(3),
.slick-slide:nth-child(5),
.slick-slide:nth-child(7),
.slick-slide:nth-child(9),
.slick-slide:nth-child(11)
</pre>
you can use:
<pre>
.slick-slide:nth-child(odd)
</pre>
;)

**Comment by badbojo** [comment]
hey
>In my opinion it's shouldn't be marked as bug (why you would like create element 1550px width for <800px width viewport?).

Sure this is the bug. v 1.3 do not have problems with this.
1550px width element only for sample.

Authors site have same problem with small width thumbs.
http://gyazo.com/d7069e600c12aa83e738eb239d0f465a

**Comment by tomaszpoliszuk** [comment]
Yup, sorry my bad - now i see.
Slider creates four .slick-cloned elements while wrapper (.slick-track) counts only two of them to full width.

**Comment by badbojo** [comment]
Do you know how to fix it?
I would really appreciate for that.

**Comment by tomaszpoliszuk** [comment]
I don't have time right now, but quick fix would be:
use v1.3.15 ;)

**Comment by badbojo** [comment]
quick bad fix with css

`.slick-track {
width: 100000px !important;
}`

**Comment by tomaszpoliszuk** [comment]
In case of example from jsfiddle - yes, but only when you use infinite:false.

**Comment by kenwheeler** [comment]
Fellas, I'm in Florida on vacation. In the meantime, go into the setDimensions method and set your slickTrack width to like 2000000000

**Comment by mariyanang** [comment]
+1

**Comment by wynny** [comment]
+1

**Comment by artmanPT** [comment]
Hi!

In a very simple scheme also noticed that there are problems when the width of the images is greater than the width of the screen.

With these settings:

  arrows: true,
  infinite: true,
  speed: 800,
  initialSlide: 1,
  centerMode: true,
  variableWidth: true,

...when you see the next or previous image there's no problem. When the image occupies the full width of the screen, in some transitions, the slider bumps or backrolls.

**Comment by kenwheeler** [comment]
This is getting fixed soon

**Comment by kenwheeler** [comment]
Fixed on master

**Comment by Olga--Smirnova** [comment]
Hi.

Still have an issue for the small screen: slide-track goes crazy in width and as a result i have horizontal scrolling which i don't need at all.

Where is my mistake?
My image width is smaller than the small screen width.

![screen shot 2015-04-28 at 10 20 20 pm](https://cloud.githubusercontent.com/assets/9512126/7367633/f565e76c-edf4-11e4-8268-6c4d4388a3e2.png)
